### ISSUE TITLE
bp_report plots fine to a file, but the screen output is extremely strange

### ISSUE THREAD

**Issue by bryanhanson** [johnschwenck/bp#1] opened 2021-03-05 01:17 UTC
In running the example in `?bp_report`l I discovered that when the output is directed to the screen, multiple windows are opened, many plots are made and eventually things are plotted on top of each other.  Complete chaos!  Looks like the plot calls are being duplicated.  It goes on for more than 3 minutes but does eventually quit w/o error.

This is really hard to describe so I made a screen recording. I'm sending the first minute to John's e-mail since it is so big.

Plotting to a file works correctly and quickly.

Thanks!

```
R > sessionInfo()
R Under development (unstable) (2021-03-04 r80062)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bp_1.0.1

loaded via a namespace (and not attached):
 [1] fansi_0.4.2      assertthat_0.2.1 dplyr_1.0.4      crayon_1.4.1     utf8_1.1.4       grid_4.1.0      
 [7] R6_2.5.0         DBI_1.1.1        lifecycle_1.0.0  gtable_0.3.0     magrittr_2.0.1   scales_1.1.1    
[13] ggplot2_3.3.3    pillar_1.5.0     rlang_0.4.10     generics_0.1.0   vctrs_0.3.6      ellipsis_0.3.1  
[19] glue_1.4.2       purrr_0.3.4      munsell_0.5.0    compiler_4.1.0   pkgconfig_2.0.3  colorspace_2.0-0
[25] tidyselect_1.1.0 tibble_3.1.0    
```

**Comment by irinagain** [comment] 2021-07-15 19:45
Has this been resolved?

**Comment by bryanhanson** [comment] 2021-07-15 20:22
Looks like no.  If I run the example in `?bp_report` the output to the Quartz window is bizarre and much as in the movie I sent earlier.  The saved file looks fine however.  The version on GH does not appear to have changed.

R > sessionInfo()
R version 4.1.0 Patched (2021-07-03 r80596)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bp_1.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        magrittr_2.0.1    cowplot_1.1.1     tidyselect_1.1.1  munsell_0.5.0    
 [6] colorspace_2.0-2  R6_2.5.0          ragg_1.1.3        rlang_0.4.11      fansi_0.5.0      
[11] dplyr_1.0.7       tools_4.1.0       grid_4.1.0        gtable_0.3.0      utf8_1.2.1       
[16] DBI_1.1.1         systemfonts_1.0.2 ellipsis_0.3.2    digest_0.6.27     assertthat_0.2.1 
[21] tibble_3.1.2      lifecycle_1.0.0   crayon_1.4.1      textshaping_0.3.5 gridExtra_2.3    
[26] farver_2.1.0      purrr_0.3.4       ggplot2_3.3.5     vctrs_0.3.8       glue_1.4.2       
[31] labeling_0.4.2    compiler_4.1.0    pillar_1.6.1      generics_0.1.0    scales_1.1.1     
[36] lubridate_1.7.10  pkgconfig_2.0.3

**Comment by irinagain** [comment] 2021-07-15 22:02
Thank you for confirming. We will look into it. I have been bad with versioning upon bug fixes but we will get better. I will update when we have some resolution

**Comment by irinagain** [comment] 2021-08-19 15:05
We have tried but not been able to reproduce on our side unfortunately, but I suspect this is because we use Rstudio rather than base R. However, after some thinking, I just pushed an update to bp_report that I think may solve the issue for you. There is now an optional argument plot (by default set to TRUE) that you can set to FALSE to suppress automatic plotting as the report is run, but still have it saved as a file.  Here is an example to try

```
library(bp)
jhs_proc <- process_data(bp_jhs,
                         sbp = "Sys.mmHg.",
                         dbp = "Dias.mmHg.",
                         date_time = "DateTime",
                         hr = "pulse.bpm.")
# Save to the file, but suppress plotting while run
out = bp_report(jhs_proc, save_report = TRUE, plot = FALSE)
# The returned object is now of type grob, that you can still plot later using grid.arrange
# although you will also have a report saved from above so no necessary
gridExtra::grid.arrange(out)

# Don't save to file and suppress plotting while run for plotting later
out = bp_report(jhs_proc, save_report = FALSE, plot = FALSE) # creates a report without plotting
gridExtra::grid.arrange(out) # creates a plot of saved report
```
Can you please let us know whether this solution is working better for you?

**Comment by bryanhanson** [comment] 2021-08-20 01:41
Thank you Irina.  With your latest version I find that `plot = FALSE` is ignored.  However, the plot does look better, it mostly appears jammed together (so maybe I need to create a larger plot device).  The saved plot looks fine (it always has).  So overall a great improvement compared to when I first opened this issue.

I looked over the code for this function. You might want to consider the relatively new `patchwork` package for arranging all these subplots and tables.  It is much easier to lay things out, and you'll need far fewer lines of code to do it.

I'm fine to consider this issue closed, but I leave it to you to close to you in case you want to chase down the `plot = FALSE` issue, but that probably deserves it's own issue.

**Comment by irinagain** [comment] 2021-08-20 14:02
Thank you, Bryan! Indeed, I was contemplating changing to patchwork eventually (we used it for plots in our other R package `iglu`), but decided to try minimal modifications as a start. It's strange that `plot = FALSE` is ignored on your side (it works on mine :)(, but I suspect this is again graphic device dependent behavior. I am going to close the issue but we will look into `patchwork` (which then will solve the whole plot issue as well as it will create a ggplot object rather than grob). Thank you again for bringing this up

**Closed as completed by irinagain** 2021-08-20 14:02 UTC
